openapi: 3.2.0
info:
  version: 1.1.4
  title: GitHub Org Fine Grained API
  description: Use the REST API to control and manage all your GitHub organizations.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact?tags=dotcom-rest-api
  x-github-plan: ghes
  x-github-release: 3.9
servers:
- url: '{protocol}://{hostname}/api/v3'
  variables:
    hostname:
      description: Self-hosted Enterprise Server hostname
      default: HOSTNAME
    protocol:
      description: Self-hosted Enterprise Server protocol
      default: http
tags:
- name: Fine-Grained
paths:
  /orgs/{org}/repository-fine-grained-permissions:
    get:
      summary: GitHub List Repository Fine-grained Permissions for an Organization
      description: 'Lists the fine-grained permissions that can be used in custom repository roles for an organization. For more information, see "[About custom repository roles](https://docs.github.com/enterprise-server@3.9/organizations/managing-peoples-access-to-your-organization-with-roles/about-custom-repository-roles)."


        The authenticated user must be an administrator of the organization or of a repository of the organization to use this endpoint.


        OAuth app tokens and personal access tokens (classic) need the `admin:org` or `repo` scope to use this endpoint.'
      tags:
      - Fine-Grained
      operationId: listRepositoryFinegrainedPermissionsForAnOrganization
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/enterprise-server@3.9/rest/orgs/custom-roles#list-repository-fine-grained-permissions-for-an-organization
      parameters:
      - $ref: '#/components/parameters/org'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/repository-fine-grained-permission'
              examples:
                default:
                  $ref: '#/components/examples/repository-fine-grained-permission-example'
      x-github:
        githubCloudOnly: true
        enabledForGitHubApps: true
        category: orgs
        subcategory: custom-roles
      security:
      - bearerHttpAuthentication: []
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  parameters:
    org:
      name: org
      description: The organization name. The name is not case sensitive.
      in: path
      required: true
      schema:
        type: string
  schemas:
    repository-fine-grained-permission:
      title: Repository Fine-Grained Permission
      description: A fine-grained permission that protects repository resources.
      type: object
      properties:
        name:
          type: string
          example: octocat
        description:
          type: string
          example: This is an example repository
      required:
      - name
      - description
  examples:
    repository-fine-grained-permission-example:
      value:
      - name: add_assignee
        description: Assign or remove a user
      - name: remove_assignee
        description: Remove an assigned user
      - name: add_label
        description: Add or remove a label
  securitySchemes:
    bearerHttpAuthentication:
      description: Bearer Token
      type: http
      scheme: Bearer
externalDocs:
  description: GitHub Enterprise Developer Docs
  url: https://docs.github.com/enterprise-server@3.9/rest/
