openapi: 3.2.0
info:
  version: 1.1.4
  title: github-repo-actions-api Artifacts API
  description: 'Use the REST API to create, manage and control the workflow of public and

    private GitHub repositories.'
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact
servers:
- url: '{protocol}://{hostname}'
  variables:
    hostname:
      description: Self-hosted Enterprise Server hostname
      default: api.github.com
    protocol:
      description: Self-hosted Enterprise Server protocol
      default: https
tags:
- name: Artifacts
paths:
  /repos/{owner}/{repo}/actions/artifacts:
    get:
      summary: GitHub List Artifacts for Repository
      description: 'Lists all artifacts for a repository.


        Anyone with read access to the repository can use this endpoint.


        OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint with a private repository.'
      tags:
      - Artifacts
      operationId: listArtifactsForRepository
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/enterprise-server@3.9/rest/actions/artifacts#list-artifacts-for-a-repository
      parameters:
      - $ref: '#/components/parameters/owner'
      - $ref: '#/components/parameters/repo'
      - $ref: '#/components/parameters/per-page'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/artifact-name'
      - in: header
        name: Authorization
        schema:
          type: string
        example: example_value
      - in: header
        name: X-GitHub-Api-Version
        schema:
          type: string
          default: '2022-11-28'
        example: example_value
      - in: header
        name: Accept
        schema:
          type: string
          default: application/vnd.github+json
        example: example_value
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: object
                required:
                - total_count
                - artifacts
                properties:
                  total_count:
                    type: integer
                  artifacts:
                    type: array
                    items:
                      $ref: '#/components/schemas/artifact'
              examples:
                default:
                  $ref: '#/components/examples/artifact-paginated'
          headers:
            Link:
              $ref: '#/components/headers/link'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: actions
        subcategory: artifacts
      x-api-evangelist-certified: '2025-07-18'
      x-api-naftiko-published: '2025-07-25'
      security:
      - bearerHttpAuthentication: []
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /repos/{owner}/{repo}/actions/artifacts/{artifact_id}:
    get:
      summary: GitHub Get an Artifact
      description: 'Gets a specific artifact for a workflow run.


        Anyone with read access to the repository can use this endpoint.


        If the repository is private, OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.'
      tags:
      - Artifacts
      operationId: getAnArtifact
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/enterprise-server@3.9/rest/actions/artifacts#get-an-artifact
      parameters:
      - $ref: '#/components/parameters/owner'
      - $ref: '#/components/parameters/repo'
      - $ref: '#/components/parameters/artifact-id'
      - in: header
        name: Authorization
        schema:
          type: string
        example: example_value
      - in: header
        name: X-GitHub-Api-Version
        schema:
          type: string
          default: '2022-11-28'
        example: example_value
      - in: header
        name: Accept
        schema:
          type: string
          default: application/vnd.github+json
        example: example_value
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/artifact'
              examples:
                default:
                  $ref: '#/components/examples/artifact'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: actions
        subcategory: artifacts
      security:
      - bearerHttpAuthentication: []
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      summary: GitHub Delete an Artifact
      description: 'Deletes an artifact for a workflow run.

        OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.'
      tags:
      - Artifacts
      operationId: deleteAnArtifact
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/enterprise-server@3.9/rest/actions/artifacts#delete-an-artifact
      parameters:
      - $ref: '#/components/parameters/owner'
      - $ref: '#/components/parameters/repo'
      - $ref: '#/components/parameters/artifact-id'
      - in: header
        name: Authorization
        schema:
          type: string
        example: example_value
      - in: header
        name: X-GitHub-Api-Version
        schema:
          type: string
          default: '2022-11-28'
        example: example_value
      - in: header
        name: Accept
        schema:
          type: string
          default: application/vnd.github+json
        example: example_value
      responses:
        '204':
          description: Response
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: actions
        subcategory: artifacts
      security:
      - bearerHttpAuthentication: []
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /repos/{owner}/{repo}/actions/artifacts/{artifact_id}/{archive_format}:
    get:
      summary: GitHub Download an Artifact
      description: 'Gets a redirect URL to download an archive for a repository. This URL expires after 1 minute. Look for `Location:` in

        the response header to find the URL for the download. The `:archive_format` must be `zip`.


        OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.'
      tags:
      - Artifacts
      operationId: downloadAnArtifact
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/enterprise-server@3.9/rest/actions/artifacts#download-an-artifact
      parameters:
      - $ref: '#/components/parameters/owner'
      - $ref: '#/components/parameters/repo'
      - $ref: '#/components/parameters/artifact-id'
      - name: archive_format
        in: path
        required: true
        schema:
          type: string
        example: example_value
      - in: header
        name: Authorization
        schema:
          type: string
        example: example_value
      - in: header
        name: X-GitHub-Api-Version
        schema:
          type: string
          default: '2022-11-28'
        example: example_value
      - in: header
        name: Accept
        schema:
          type: string
          default: application/vnd.github+json
        example: example_value
      responses:
        '302':
          description: Response
          headers:
            Location:
              $ref: '#/components/headers/location'
        '410':
          $ref: '#/components/responses/gone'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: actions
        subcategory: artifacts
      security:
      - bearerHttpAuthentication: []
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /repos/{owner}/{repo}/actions/runs/{run_id}/artifacts:
    get:
      summary: GitHub List Workflow Run Artifacts
      description: 'Lists artifacts for a workflow run.


        Anyone with read access to the repository can use this endpoint.


        OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint with a private repository.'
      tags:
      - Artifacts
      operationId: listWorkflowRunArtifacts
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/enterprise-server@3.9/rest/actions/artifacts#list-workflow-run-artifacts
      parameters:
      - $ref: '#/components/parameters/owner'
      - $ref: '#/components/parameters/repo'
      - $ref: '#/components/parameters/run-id'
      - $ref: '#/components/parameters/per-page'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/artifact-name'
      - in: header
        name: Authorization
        schema:
          type: string
        example: example_value
      - in: header
        name: X-GitHub-Api-Version
        schema:
          type: string
          default: '2022-11-28'
        example: example_value
      - in: header
        name: Accept
        schema:
          type: string
          default: application/vnd.github+json
        example: example_value
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: object
                required:
                - total_count
                - artifacts
                properties:
                  total_count:
                    type: integer
                  artifacts:
                    type: array
                    items:
                      $ref: '#/components/schemas/artifact'
              examples:
                default:
                  $ref: '#/components/examples/artifact-paginated'
          headers:
            Link:
              $ref: '#/components/headers/link'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: actions
        subcategory: artifacts
      security:
      - bearerHttpAuthentication: []
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  examples:
    artifact:
      value:
        id: 11
        node_id: MDg6QXJ0aWZhY3QxMQ==
        name: Rails
        size_in_bytes: 556
        url: https://api.github.com/repos/octo-org/octo-docs/actions/artifacts/11
        archive_download_url: https://api.github.com/repos/octo-org/octo-docs/actions/artifacts/11/zip
        expired: false
        created_at: '2020-01-10T14:59:22Z'
        expires_at: '2020-01-21T14:59:22Z'
        updated_at: '2020-01-21T14:59:22Z'
        workflow_run:
          id: 2332938
          repository_id: 1296269
          head_repository_id: 1296269
          head_branch: main
          head_sha: 328faa0536e6fef19753d9d91dc96a9931694ce3
    artifact-paginated:
      value:
        total_count: 2
        artifacts:
        - id: 11
          node_id: MDg6QXJ0aWZhY3QxMQ==
          name: Rails
          size_in_bytes: 556
          url: https://api.github.com/repos/octo-org/octo-docs/actions/artifacts/11
          archive_download_url: https://api.github.com/repos/octo-org/octo-docs/actions/artifacts/11/zip
          expired: false
          created_at: '2020-01-10T14:59:22Z'
          expires_at: '2020-03-21T14:59:22Z'
          updated_at: '2020-02-21T14:59:22Z'
          workflow_run:
            id: 2332938
            repository_id: 1296269
            head_repository_id: 1296269
            head_branch: main
            head_sha: 328faa0536e6fef19753d9d91dc96a9931694ce3
        - id: 13
          node_id: MDg6QXJ0aWZhY3QxMw==
          name: Test output
          size_in_bytes: 453
          url: https://api.github.com/repos/octo-org/octo-docs/actions/artifacts/13
          archive_download_url: https://api.github.com/repos/octo-org/octo-docs/actions/artifacts/13/zip
          expired: false
          created_at: '2020-01-10T14:59:22Z'
          expires_at: '2020-03-21T14:59:22Z'
          updated_at: '2020-02-21T14:59:22Z'
          workflow_run:
            id: 2332942
            repository_id: 1296269
            head_repository_id: 1296269
            head_branch: main
            head_sha: 178f4f6090b3fccad4a65b3e83d076a622d59652
  schemas:
    artifact:
      title: Artifact
      description: An artifact
      type: object
      properties:
        id:
          type: integer
          example: 5
        node_id:
          type: string
          example: MDEwOkNoZWNrU3VpdGU1
        name:
          description: The name of the artifact.
          type: string
          example: AdventureWorks.Framework
        size_in_bytes:
          description: The size in bytes of the artifact.
          type: integer
          example: 12345
        url:
          type: string
          example: https://api.github.com/repos/github/hello-world/actions/artifacts/5
        archive_download_url:
          type: string
          example: https://api.github.com/repos/github/hello-world/actions/artifacts/5/zip
        expired:
          description: Whether or not the artifact has expired.
          type: boolean
          example: true
        created_at:
          type: string
          format: date-time
          example: '2026-04-17T12:00:00Z'
        expires_at:
          type: string
          format: date-time
          example: '2026-04-17T12:00:00Z'
        updated_at:
          type: string
          format: date-time
          example: '2026-04-17T12:00:00Z'
        workflow_run:
          type: object
          properties:
            id:
              example: 10
              type: integer
            repository_id:
              example: 42
              type: integer
            head_repository_id:
              example: 42
              type: integer
            head_branch:
              example: main
              type: string
            head_sha:
              example: 009b8a3a9ccbb128af87f9b1c0f4c62e8a304f6d
              type: string
      required:
      - id
      - node_id
      - name
      - size_in_bytes
      - url
      - archive_download_url
      - expired
      - created_at
      - expires_at
      - updated_at
    basic-error:
      title: Basic Error
      description: Basic Error
      type: object
      properties:
        message:
          type: string
          example: Example body text
        documentation_url:
          type: string
          example: https://api.github.com/repos/octocat/Hello-World
        url:
          type: string
          example: https://api.github.com/repos/octocat/Hello-World
        status:
          type: string
          example: open
  responses:
    gone:
      description: Gone
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/basic-error'
  headers:
    location:
      example: https://pipelines.actions.githubusercontent.com/OhgS4QRKqmgx7bKC27GKU83jnQjyeqG8oIMTge8eqtheppcmw8/_apis/pipelines/1/runs/176/signedlogcontent?urlExpires=2020-01-24T18%3A10%3A31.5729946Z&urlSigningMethod=HMACV1&urlSignature=agG73JakPYkHrh06seAkvmH7rBR4Ji4c2%2B6a2ejYh3E%3D
      schema:
        type: string
    link:
      example: <https://api.github.com/resource?page=2>; rel="next", <https://api.github.com/resource?page=5>; rel="last"
      schema:
        type: string
  parameters:
    artifact-id:
      name: artifact_id
      description: The unique identifier of the artifact.
      in: path
      required: true
      schema:
        type: integer
    run-id:
      name: run_id
      description: The unique identifier of the workflow run.
      in: path
      required: true
      schema:
        type: integer
    per-page:
      name: per_page
      description: The number of results per page (max 100). For more information, see "[Using pagination in the REST API](https://docs.github.com/enterprise-server@3.9/rest/using-the-rest-api/using-pagination-in-the-rest-api)."
      in: query
      schema:
        type: integer
        default: 30
    artifact-name:
      name: name
      description: The name field of an artifact. When specified, only artifacts with this name will be returned.
      in: query
      required: false
      schema:
        type: string
    owner:
      name: owner
      description: The account owner of the repository. The name is not case sensitive.
      in: path
      required: true
      schema:
        type: string
    repo:
      name: repo
      description: The name of the repository without the `.git` extension. The name is not case sensitive.
      in: path
      required: true
      schema:
        type: string
    page:
      name: page
      description: The page number of the results to fetch. For more information, see "[Using pagination in the REST API](https://docs.github.com/enterprise-server@3.9/rest/using-the-rest-api/using-pagination-in-the-rest-api)."
      in: query
      schema:
        type: integer
        default: 1
  securitySchemes:
    bearerHttpAuthentication:
      description: Bearer Token
      type: http
      scheme: Bearer
externalDocs:
  description: GitHub Enterprise Developer Docs
  url: https://docs.github.com/enterprise-server@3.9/rest/
