openapi: 3.2.0
info:
  version: 1.1.4
  title: GitHub Manage Node API
  description: Needs description.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact?tags=dotcom-rest-api
  x-github-plan: ghes
  x-github-release: 3.9
servers:
- url: '{protocol}://{hostname}/api/v3'
  variables:
    hostname:
      description: Self-hosted Enterprise Server hostname
      default: HOSTNAME
    protocol:
      description: Self-hosted Enterprise Server protocol
      default: http
tags:
- name: Node
paths:
  /manage/v1/config/nodes:
    get:
      summary: GitHub Get Ghes Node Metadata for All Nodes
      description: Get node metadata for all configured nodes in the current cluster. For more information, see "[About clustering](https://docs.github.com/enterprise-server@3.9/admin/enterprise-management/configuring-clustering/about-clustering)."
      operationId: getGhesNodeMetadataForAllNodes
      tags:
      - Node
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/manage-ghes#get-ghes-node-metadata-for-all-nodes
      servers:
      - url: '{protocol}://{hostname}'
        variables:
          hostname:
            default: HOSTNAME
            description: Self-hosted Enterprise Server hostname
          protocol:
            default: http
            description: Self-hosted Enterprise Server protocol
      parameters:
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/cluster-roles'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ghes-config-nodes'
              examples:
                default:
                  $ref: '#/components/examples/ghes-config-nodes'
        '401':
          description: Unauthorized
        '500':
          description: Internal error
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-admin
        subcategory: manage-ghes
      security:
      - bearerHttpAuthentication: []
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  parameters:
    cluster-roles:
      name: cluster_roles
      description: The cluster roles from the cluster configuration file.
      in: query
      required: false
      schema:
        type: string
    uuid:
      name: uuid
      description: The UUID which identifies a node.
      in: query
      required: false
      schema:
        type: string
  examples:
    ghes-config-nodes:
      value:
        topology: Cluster
        nodes:
        - hostname: data1
          uuid: 1b6cf518-f97c-11ed-8544-061d81f7eedb
          cluster_roles:
          - ConsulServer
          - ElasticsearchServer
          - GitServer
          - StorageServer
        - hostname: data2
          uuid: 228406d4-f97c-11ed-ab01-062281bbcf03
          cluster_roles:
          - ElasticsearchServer
          - StorageServer
          - PagesServer
  schemas:
    ghes-config-nodes:
      type: object
      properties:
        topology:
          $ref: '#/components/schemas/ghes-cluster-topology'
        nodes:
          type: array
          items:
            type: object
            properties:
              hostname:
                type: string
              uuid:
                type: string
              replica:
                type: boolean
              cluster_roles:
                type: array
                items:
                  $ref: '#/components/schemas/ghes-cluster-roles'
    ghes-cluster-topology:
      type: string
      enum:
      - SingleNode
      - Ha
      - Cluster
  securitySchemes:
    bearerHttpAuthentication:
      description: Bearer Token
      type: http
      scheme: Bearer
externalDocs:
  description: GitHub Enterprise Developer Docs
  url: https://docs.github.com/enterprise-server@3.9/rest/
