openapi: 3.2.0
info:
  version: 1.1.4
  title: GitHub Org Announcement API
  description: Use the REST API to control and manage all your GitHub organizations.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact?tags=dotcom-rest-api
  x-github-plan: ghes
  x-github-release: 3.9
servers:
- url: '{protocol}://{hostname}/api/v3'
  variables:
    hostname:
      description: Self-hosted Enterprise Server hostname
      default: HOSTNAME
    protocol:
      description: Self-hosted Enterprise Server protocol
      default: http
tags:
- name: Announcement
paths:
  /orgs/{org}/announcement:
    get:
      summary: GitHub Get Announcement Banner for Organization
      description: 'Gets the announcement banner currently set for the organization. Only returns the announcement banner set at the

        organization level. Organization members may also see an enterprise-level announcement banner. To get an

        announcement banner displayed at the enterprise level, use the enterprise-level endpoint.'
      tags:
      - Announcement
      operationId: getAnnouncementBannerForOrganization
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/enterprise-server@3.9/rest/announcement-banners/organizations#get-announcement-banner-for-organization
      parameters:
      - $ref: '#/components/parameters/org'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/announcement-banner'
              examples:
                default:
                  $ref: '#/components/examples/announcement'
      x-github:
        githubCloudOnly: true
        enabledForGitHubApps: true
        category: announcement-banners
        subcategory: organizations
      security:
      - bearerHttpAuthentication: []
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    patch:
      summary: GitHub Set Announcement Banner for Organization
      description: Sets the announcement banner to display for the organization.
      tags:
      - Announcement
      operationId: setAnnouncementBannerForOrganization
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/enterprise-server@3.9/rest/announcement-banners/organizations#set-announcement-banner-for-organization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/announcement'
            examples:
              default:
                $ref: '#/components/examples/announcement'
      parameters:
      - $ref: '#/components/parameters/org'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/announcement-banner'
              examples:
                default:
                  $ref: '#/components/examples/announcement'
      x-github:
        githubCloudOnly: true
        enabledForGitHubApps: true
        category: announcement-banners
        subcategory: organizations
      security:
      - bearerHttpAuthentication: []
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      summary: GitHub Remove Announcement Banner from Organization
      description: Removes the announcement banner currently set for the organization.
      tags:
      - Announcement
      operationId: removeAnnouncementBannerFromOrganization
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/enterprise-server@3.9/rest/announcement-banners/organizations#remove-announcement-banner-from-organization
      parameters:
      - $ref: '#/components/parameters/org'
      responses:
        '204':
          description: Response
      x-github:
        githubCloudOnly: true
        enabledForGitHubApps: true
        category: announcement-banners
        subcategory: organizations
      security:
      - bearerHttpAuthentication: []
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    announcement-message:
      type:
      - string
      - 'null'
      description: The announcement text in GitHub Flavored Markdown. For more information about GitHub Flavored Markdown, see "[Basic writing and formatting syntax](https://docs.github.com/enterprise-server@3.9/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)."
      example: Very **important** announcement about _something_.
    announcement-banner:
      title: Announcement Banner
      description: Announcement at either the repository, organization, or enterprise level
      type: object
      properties:
        announcement:
          $ref: '#/components/schemas/announcement-message'
        expires_at:
          $ref: '#/components/schemas/announcement-expiration'
        user_dismissible:
          $ref: '#/components/schemas/announcement-user-dismissible'
      required:
      - announcement
      - expires_at
      - user_dismissible
    announcement:
      title: Enterprise Announcement
      description: Enterprise global announcement
      type: object
      properties:
        announcement:
          $ref: '#/components/schemas/announcement-message'
        expires_at:
          $ref: '#/components/schemas/announcement-expiration'
      required:
      - announcement
    announcement-user-dismissible:
      type:
      - boolean
      - 'null'
      description: Whether an announcement can be dismissed by the user.
      example: false
      default: false
    announcement-expiration:
      type:
      - string
      - 'null'
      format: date-time
      description: 'The time at which the announcement expires. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`. To set an announcement that never expires, omit this parameter, set it to `null`, or set it to an empty string.'
      example: '"2021-01-01T00:00:00.000-07:00"'
  examples:
    announcement:
      summary: Announcement banner
      value:
        announcement: Very **important** announcement about _something_.
        expires_at: '2021-01-01T00:00:00.000+00:00'
        user_dismissible: false
  parameters:
    org:
      name: org
      description: The organization name. The name is not case sensitive.
      in: path
      required: true
      schema:
        type: string
  securitySchemes:
    bearerHttpAuthentication:
      description: Bearer Token
      type: http
      scheme: Bearer
externalDocs:
  description: GitHub Enterprise Developer Docs
  url: https://docs.github.com/enterprise-server@3.9/rest/
