openapi: 3.2.0
info:
  version: 1.1.4
  title: GitHub Org Feature API
  description: Use the REST API to control and manage all your GitHub organizations.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact?tags=dotcom-rest-api
  x-github-plan: ghes
  x-github-release: 3.9
servers:
- url: '{protocol}://{hostname}/api/v3'
  variables:
    hostname:
      description: Self-hosted Enterprise Server hostname
      default: HOSTNAME
    protocol:
      description: Self-hosted Enterprise Server protocol
      default: http
tags:
- name: Feature
paths:
  /orgs/{org}/{security_product}/{enablement}:
    post:
      summary: GitHub Enable or Disable Security Feature for an Organization
      description: 'Enables or disables the specified security feature for all eligible repositories in an organization. For more information, see "[Managing security managers in your organization](https://docs.github.com/enterprise-server@3.9/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization)."


        The authenticated user must be an organization owner or be member of a team with the security manager role to use this endpoint.


        OAuth app tokens and personal access tokens (classic) need the `write:org` scope to use this endpoint.'
      tags:
      - Feature
      operationId: enableOrDisableSecurityFeatureForAnOrganization
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/enterprise-server@3.9/rest/orgs/orgs#enable-or-disable-a-security-feature-for-an-organization
      parameters:
      - $ref: '#/components/parameters/org'
      - $ref: '#/components/parameters/security-product'
      - $ref: '#/components/parameters/org-security-product-enablement'
      responses:
        '204':
          description: Action started
        '422':
          description: The action could not be taken due to an in progress enablement, or a policy is preventing enablement
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        previews: []
        category: orgs
        subcategory: orgs
      security:
      - bearerHttpAuthentication: []
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  parameters:
    security-product:
      name: security_product
      in: path
      description: The security feature to enable or disable.
      required: true
      schema:
        type: string
        enum:
        - dependency_graph
        - dependabot_alerts
        - dependabot_security_updates
        - advanced_security
        - code_scanning_default_setup
        - secret_scanning
        - secret_scanning_push_protection
    org:
      name: org
      description: The organization name. The name is not case sensitive.
      in: path
      required: true
      schema:
        type: string
    org-security-product-enablement:
      name: enablement
      in: path
      description: 'The action to take.


        `enable_all` means to enable the specified security feature for all repositories in the organization.

        `disable_all` means to disable the specified security feature for all repositories in the organization.'
      required: true
      schema:
        type: string
        enum:
        - enable_all
        - disable_all
  securitySchemes:
    bearerHttpAuthentication:
      description: Bearer Token
      type: http
      scheme: Bearer
externalDocs:
  description: GitHub Enterprise Developer Docs
  url: https://docs.github.com/enterprise-server@3.9/rest/
