openapi: 3.2.0
info:
  version: 1.1.4
  title: github-repos-api Large File Storage API
  description: 'Use the REST API to create, manage and control the workflow of public and

    private GitHub repositories.'
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact
servers:
- url: '{protocol}://{hostname}'
  variables:
    hostname:
      description: Self-hosted Enterprise Server hostname
      default: api.github.com
    protocol:
      description: Self-hosted Enterprise Server protocol
      default: https
tags:
- name: Large File Storage
paths:
  /repos/{owner}/{repo}/lfs:
    put:
      summary: GitHub Enable Git Lfs for Repository
      description: 'Enables Git LFS for a repository.


        OAuth app tokens and personal access tokens (classic) need the `admin:enterprise` scope to use this endpoint.'
      operationId: enableGitLfsForRepository
      tags:
      - Large File Storage
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/enterprise-server@3.9/rest/repos/lfs#enable-git-lfs-for-a-repository
      parameters:
      - $ref: '#/components/parameters/owner'
      - $ref: '#/components/parameters/repo'
      - in: header
        name: Authorization
        schema:
          type: string
        example: example_value
      - in: header
        name: X-GitHub-Api-Version
        schema:
          type: string
          default: '2022-11-28'
        example: example_value
      - in: header
        name: Accept
        schema:
          type: string
          default: application/vnd.github+json
        example: example_value
      responses:
        '202':
          $ref: '#/components/responses/accepted'
        '403':
          description: 'We will return a 403 with one of the following messages:


            - Git LFS support not enabled because Git LFS is globally disabled.

            - Git LFS support not enabled because Git LFS is disabled for the root repository in the network.

            - Git LFS support not enabled because Git LFS is disabled for <owner>.'
      x-github:
        githubCloudOnly: true
        enabledForGitHubApps: false
        category: repos
        subcategory: lfs
      security:
      - bearerHttpAuthentication: []
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      summary: GitHub Disable Git Lfs for Repository
      description: 'Disables Git LFS for a repository.


        OAuth app tokens and personal access tokens (classic) need the `admin:enterprise` scope to use this endpoint.'
      operationId: disableGitLfsForRepository
      tags:
      - Large File Storage
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/enterprise-server@3.9/rest/repos/lfs#disable-git-lfs-for-a-repository
      parameters:
      - $ref: '#/components/parameters/owner'
      - $ref: '#/components/parameters/repo'
      - in: header
        name: Authorization
        schema:
          type: string
        example: example_value
      - in: header
        name: X-GitHub-Api-Version
        schema:
          type: string
          default: '2022-11-28'
        example: example_value
      - in: header
        name: Accept
        schema:
          type: string
          default: application/vnd.github+json
        example: example_value
      responses:
        '204':
          description: Response
      x-github:
        githubCloudOnly: true
        enabledForGitHubApps: false
        category: repos
        subcategory: lfs
      security:
      - bearerHttpAuthentication: []
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  parameters:
    owner:
      name: owner
      description: The account owner of the repository. The name is not case sensitive.
      in: path
      required: true
      schema:
        type: string
    repo:
      name: repo
      description: The name of the repository without the `.git` extension. The name is not case sensitive.
      in: path
      required: true
      schema:
        type: string
  responses:
    accepted:
      description: Accepted
      content:
        application/json:
          schema:
            type: object
          examples:
            default:
              value: {}
  securitySchemes:
    bearerHttpAuthentication:
      description: Bearer Token
      type: http
      scheme: Bearer
externalDocs:
  description: GitHub Enterprise Developer Docs
  url: https://docs.github.com/enterprise-server@3.9/rest/
